Branch find 2
AY2021S2-TIC4002-F18-2/tp2 pull request #75
Opened 2021-03-15 15:33 UTC by dgc5213

Edit Find command, DG, UG. 
closes #65 , closes #69

2021-03-15 15:40 UTC, dgc5213 commented
Hi @e0260222 , Please help merge it . thanks

2021-03-15 16:39 UTC, e0260222 requested changes
Your changes look great! Perhaps you could address the changes that I've suggested

2021-03-15 16:39 UTC, e0260222 commented on docs/UserGuide.md
>  * If `TYPE` is `n`, the search will be based on name `[n/NAME]`.
Perhaps `[n/NAME]` should be removed?

2021-03-15 16:39 UTC, e0260222 commented on docs/UserGuide.md
>  * If `TYPE` is `r`, the search will be based on role `[r/ROLE]`.
Perhaps `[r/ROLE]` should be removed?

2021-03-16 11:52 UTC, e0260222 approved these changes
LGTM

2021-03-16 11:52 UTC, merged